<a href="https://colab.research.google.com/github/Grim705/Colab_Neural_Network/blob/main/NeuralNetwork_py0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Resource: https://www.learnpytorch.io/00_pytorch_fundamentals/

### Tensor
Numpy array: A numpy array is a grid of values, all of the same type, and is indexed by a tuple of nonnegative integers.

Tensor is just like, numpy array.

Tensor is also known as data container.


In [ ]:
import torch

In [ ]:
print("Hello")

Hello


In [ ]:
print(torch.__version__)


2.0.1+cu118


Creating Tensors:

In [ ]:
## Scaler Tensor
scaler = torch.tensor(8)
scaler


tensor(8)

In [ ]:
# Default datatype of pytorch tensor is float. until explicitly defined
scaler.dtype

torch.int64

In [ ]:
## Sclaer tensor has no dimentions.
print(scaler.ndim)
## .item() will return the tensor as python int.
scaler.item()

0


8

Scaler does not have shape because it does not have an axis.
The shape of a tensor is determined by the length of each axis, so if we know the shape of a given tensor, then we know the length of each axis.
Here is a "scalar" or "rank-0" tensor . A scalar contains a single value, and no "axes".

In [ ]:
scaler.shape

torch.Size([])

In [ ]:
# Vector
vector = torch.tensor([7, 9])
vector

tensor([7, 9])

In [ ]:
vector.item

<function Tensor.item>

In [ ]:
# Vector Dimentions
print(vector.ndim)
# Shape of a vector
vector.shape

1


torch.Size([2])

The difference between dimensions and shape is:
1. ndim returns INT type, the number of dimentions in the tensor. ndim is equivalent to 'ndim' of Numpy arrays. whereas
2. shape return a tuple of number of elements in each dimentions of the tensor. the 'shape' of pytorch tensor is  equivalent to 'shape' attribute of Numpy array. A shape can also be said as the length of each axis(dimensions).



In [ ]:
# Matrix
MATRIX = torch.tensor([[7, 8],
                       [9, 10.7]])
MATRIX

tensor([[ 7.0000,  8.0000],
        [ 9.0000, 10.7000]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

why [1, 3, 3]?
bcz, the TENSOR has 3 dimensions
1. In the dim=0 it has 1 element where the element is itself a tensor.
2. In the dim=1 it has 3 elements which are "1-dimension tensors".
3. In the dim=2 it has 3 elements in each "1-dim tensors".

Further read it on: https://www.learnpytorch.io/00_pytorch_fundamentals/

In [ ]:
x.shape # it is an attribute.
# both returns the same thing

torch.Size([3, 4])

In [ ]:
x.size() # this is a function.

torch.Size([3, 4])

# Random Tensors
Why random tensors?

Random tensor sare important because the way nural networks learns is that they start with tensors full of random numbers and then adjust those ranndom numbers to better represent the data.

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`


In [ ]:
# create a random tensoor of size (3, 4)
random_tensor = torch.rand(0)
random_tensor

tensor([])

In [ ]:
random_tensor.ndim

1

In [ ]:
tensor = torch.tensor([])

In [ ]:
tensor.ndim

1

In [ ]:
tensor.shape

torch.Size([0])

In [ ]:
rnd_ten = torch.rand(10, 10, 10)
rnd_ten

tensor([[[4.3176e-01, 1.3141e-01, 6.8434e-01, 8.6312e-01, 1.5119e-01,
          6.6881e-01, 9.0970e-01, 8.9952e-01, 8.1086e-01, 9.7743e-01],
         [7.9128e-01, 6.1333e-01, 5.0580e-01, 1.8803e-01, 7.9495e-01,
          7.9954e-01, 4.4633e-01, 3.3856e-01, 7.5537e-01, 7.2052e-01],
         [1.4276e-01, 6.0663e-01, 3.8606e-01, 6.3782e-01, 1.0673e-01,
          2.6098e-01, 4.4448e-01, 9.2990e-02, 2.7937e-01, 3.4200e-01],
         [3.5328e-03, 3.9373e-01, 8.1085e-01, 6.8922e-01, 5.5892e-01,
          8.5836e-01, 6.9280e-01, 5.4993e-01, 3.5355e-01, 3.1639e-01],
         [3.5951e-01, 8.3514e-01, 2.8172e-01, 9.4151e-01, 1.1711e-02,
          5.6191e-01, 3.0901e-01, 7.5081e-01, 2.2129e-01, 2.3014e-02],
         [3.7301e-01, 5.7073e-01, 2.8031e-01, 4.1069e-01, 7.9211e-01,
          8.6244e-01, 1.8108e-01, 5.4557e-01, 5.0305e-01, 3.4990e-01],
         [7.4823e-01, 6.7528e-01, 1.0987e-01, 7.8293e-01, 6.2224e-01,
          4.6723e-01, 7.5436e-01, 2.3825e-01, 4.5611e-01, 1.0622e-01],
         [7.2

In [ ]:
rnd_ten.ndim

3

# Creating Tensor similar shape to an image tensor.

Follow : https://www.learnpytorch.io/00_pytorch_fundamentals/

In [ ]:
random_image_size_tensor = torch.rand(size=(3, 224, 224)) # colour channels (R, B, G), height, width
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

# Zeros and ones tensors


In [ ]:
# creating a tensor fo all zeros
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

Zeros tensors are used to hide unnecessary data in the tensor and alows machine to focus on the actual ones.
For exp: `zeros*rnd_ten` will convert all the numbers into zeros, similarly if we wanted to hide only a row we can just multiply that row with zeros in order tell the machine to ingore the row.
More commonly used than ones.

In [ ]:
# creating a tensor of all ones
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype


torch.float32

# Creating a range of tensors and tensors-like

In [ ]:
torch.range(0, 10)

<ipython-input-12-cf0dcdb325c8>:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0, 10)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

Using `torch.range()` will get deprecated message, therefore use `torch.arange()`.
Good for future use.

In [ ]:
torch.arange(0, 10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# Creating tensor of range 0 to 1000 with a step of 77

range = torch.arange(start=0, end=1000, step=77)
range

tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924])

In [ ]:
range.dtype

torch.int64

In [ ]:
# Creating tensors-like
ten_zeros = torch.zeros_like(input=range)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
ten_zeros.dtype

torch.int64

Here we got `ten_zeros` in the same shape as `range` tensor.
It creates a similar tensor `like` with whatever methods are given.

# TENSOR DATA TYPE

Single precision: Float32

Double precision: Float64

Half precision: Float16

precision in computer sscience can be said as the accuracy of the processor or GPU to calculate complex numbers.
IEEE 754

```
Read more on net.
```



In [ ]:
# Float 32 tensor
f32 = torch.tensor([3.0, 6.0, 9.0],
                   dtype = None)
f32

tensor([3., 6., 9.])

In [ ]:
f32.dtype

torch.float32

In [ ]:
f16 = torch.tensor([3, 4, 6],
                   dtype = torch.float16)
f16

tensor([3., 4., 6.], dtype=torch.float16)

In [ ]:
f16.dtype

torch.float16

**Tensors datatyes**

**Important Note:** Tensors datatypes is one of the 3 big errors you"ll run into with pytorch & deep learning.
1. Tensors not right datatype.
2. Tesnsors not right shape.
3. Tensors not on the right or same device.


In [ ]:
# float 32 tensor with
f32 = torch.tensor([3.0, 4.0, 5.0],
                   dtype = None, # what data type is the tensor
                   device= None, # allows to change the runtime type from `cpu` as the defalut to 'cuda' for gpu accelerated.
                   requires_grad= False)
f32


tensor([3., 4., 5.])

In [ ]:
# float 32 tensor with
f32 = torch.tensor([3.0, 4.0, 5.0],
                   dtype = None, # what data type is the tensor
                   device= "cpu", # allows to change the runtime type from `cpu` as the defalut to 'cuda' for gpu accelerated.
                   requires_grad= False)
f32


tensor([3., 4., 5.])

In [ ]:
# float 32 tensor with
f32 = torch.tensor([3.0, 4.0, 5.0],
                   dtype = None, # what data type is the tensor
                   device= "cuda", # allows to change the runtime type from `cpu` as the defalut to 'cuda' for gpu accelerated.
                   requires_grad= False) # whether or not to track gradeints with this operations.
f32

In [ ]:
# converting to Float 16
f16 = f32.type(torch.float16)
f16

tensor([3., 4., 5.], dtype=torch.float16)

In [ ]:
# As above mentioned there likely to be an error if we try to perform tensors operations if the the tensors are not in the same or right datatype.
# Here we can multiply f16 tensor with a f32 tensor. how?
f = f16 * f32
f

tensor([ 9., 16., 25.])

In [ ]:
f.dtype
# we get f32 type tensor as a result. why?

torch.float32

In [ ]:
# Integer tensor
int32 = torch.tensor([3, 4, 5],
                     dtype= torch.int32)
int32

tensor([3, 4, 5], dtype=torch.int32)

In [ ]:
f32 * int32 # it works as well

tensor([ 9., 16., 25.])

Getting information from tensor

1. Tensors not right datatype. - to get datatype from a tensor, can use `tensor.dtype`.
2. Tesnsors not right shape. - to get shape from a tensor, can use `tensor.shape`
3. Tensors not on the right or same device. - to get device from a tensor, can use `tensor.device`.


In [ ]:
x = torch.rand(3, 4)
x

tensor([[0.4300, 0.9426, 0.3194, 0.2596],
        [0.4295, 0.1005, 0.1687, 0.5944],
        [0.2828, 0.4955, 0.8998, 0.8403]])

In [ ]:
# details about x tensor
print(x)
print(f"Datatype of Tensor: {x.dtype}") # this is called formatting string litteral.
print(f"Shape of tensor: {x.shape}")
print(f"device tensor is on: {x.device}") # defalut device is cpu.


tensor([[0.4300, 0.9426, 0.3194, 0.2596],
        [0.4295, 0.1005, 0.1687, 0.5944],
        [0.2828, 0.4955, 0.8998, 0.8403]])
Datatype of Tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
device tensor is on: cpu


In [ ]:
# creating a random tensor of float16 datatype.
random = torch.rand(size=(3, 4),
                    dtype = torch.float16,
                    device = "cpu")
random

tensor([[0.4614, 0.2939, 0.1782, 0.6816],
        [0.3159, 0.8677, 0.2300, 0.0693],
        [0.0195, 0.0024, 0.7578, 0.3105]], dtype=torch.float16)

In [ ]:
print(f"Random tensor of Float16 type: {random.dtype}")
print(f"Random tensor on cpu: {random.device}")


Random tensor of Float16 type: torch.float16
Random tensor on cpu: cpu


# Tensor Manipulations
1. Additions
2. Substractions
3. Multiplications (Element wise)
4. Divisions
5. Matrix Multiplications


In [ ]:
# Addition
tensor = torch.tensor([1, 2, 3])
tensor + 10


tensor([11, 12, 13])

In [ ]:
# Multiplication tensor (element wise)
tensor * 10

tensor([10, 20, 30])

In [ ]:
# Substraction
tensor - 10

tensor([-9, -8, -7])

In [ ]:
# pyTorch in-built fuctions for operations
torch.mul(tensor, 10)
torch.add(tensor, 10)
torch.sub(tensor, 10)
torch.div(tensor, 10)

tensor([0.1000, 0.2000, 0.3000])

### Matrix Multiplication

Two main ways of performing multiplication in neural networks and deep learning:

1. Element-wise multiplication
2. Matrix multiplication (Dot product)


In [ ]:
# Element-wise multiplication
tensor * tensor


tensor([1, 4, 9])

In [ ]:
# Matrix Multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [ ]:
%%time
# Time taking
value = 0
for i in range(len(tensor)):
  value += tensor * tensor
print(value)

tensor([ 3, 12, 27])
CPU times: user 3.21 ms, sys: 15 µs, total: 3.22 ms
Wall time: 2.91 ms


In [ ]:
%%time
torch.matmul(tensor, tensor)
# 10x faster

CPU times: user 113 µs, sys: 0 ns, total: 113 µs
Wall time: 117 µs


tensor(14)

**Shape errors**
There are two main rules that performing matrix multiplication needs to satisfy:
1. The **inner dimensions** must be same.
* `(3, 4) @ (3, 2)` won't work
* `(2 ,3) @ (3 ,2)` will work
* `(3, 2) @ (2, 3)` will

*Here @ is symbol for matrix multiplication it is simililar to `torch.matmul()` method*

2. The resulting matrix has the shape of the **outer dimensions**:
* `(2, 3) @ (3, 2) -> (2, 2)`

*Matrixmultiplication.xzy* -- website

In [ ]:
tensor_A = torch.tensor([[1, 2],
                        [3, 4],
                        [5, 6]])
tensor_B = torch.tensor([[7, 8],
                        [9, 10],
                         [11, 12]])
torch.matmul(tensor_A, tensor_B)


RuntimeError: ignored

In [ ]:
# To fix such shape errors, we use **transpose** `.T`.
tensor_B.T


tensor([[ 7,  9, 11],
        [ 8, 10, 12]])

In [ ]:
# We get an result.
torch.matmul(tensor_A, tensor_B.T)


tensor([[ 23,  29,  35],
        [ 53,  67,  81],
        [ 83, 105, 127]])

### Tensor Aggregation, Min, Max, sum, Mean.

In [ ]:
# Maxima and Minima of tensors
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
# Find Min
torch.min(x), x.min()


(tensor(0), tensor(0))

In [ ]:
torch.max(x), x.max()

(tensor(90), tensor(90))

Here in below code the mean takes input of type floating point or complex dtype.
Instead it got long.


In [ ]:
torch.mean(x)

RuntimeError: ignored

In [ ]:
# correct format
torch.mean(x.type(torch.float32)) # changed to floating point.

tensor(45.)

In [ ]:
torch.sum(x), x.sum()

(tensor(450), tensor(450))

### Finding the positional Min and Max

In [ ]:
x = torch.arange(1, 100, 10)
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

Find the position in tensor:
* That has the minimum value with `argmin()` -> retruns the index position of target tensor where the minimum value occurs.
* That has the maximum value with `argmax()` -> retruns the index position of target tensor where the maximum value occurs.

In [ ]:
x.argmin() # returns the index value

tensor(0)

In [ ]:
x[0] # returning the element

tensor(1)

In [ ]:
# Finding the max position.
x.argmax() # retruns the index with max element.

tensor(9)

### Reshaping, Stcking, Squeezing and Unsqueezing tensors.
* Reshaping - reshapes an input tensor tensor to a defined shape.
* Veiw - Return a view of an inpit tensor of certain shape but keep the same memory as the original tensor.
* Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack).
* Squeeze - removes all `1` dimension sfrom a tensor.
* Unsquueze - add a `1` dimension to a target tensor.
* Permute - Return a view of the input with dimensions permuted (swapped) in a certain way.


In [ ]:
import torch

In [ ]:
a = torch.arange(1., 10.) #manuall
a, a.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
a_reshaped = a.reshape(1, 9)
a_reshaped, a_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
a_reshaped = a.reshape(9, 1)
a_reshaped, a_reshaped.shape, x.ndim

NameError: ignored

In [ ]:
# Changing the view
z = a.view(1, 9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

*View of a tensor shares the same memory as the original tensor, therefore changing z changes a.*

In [ ]:
# Changing the z changes the a
z[:, 0] = 5 #Slicing of 2-D tensor. : -> selecting all the row elements, 0 -> slecting the first element of the coulumn.
z, a

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [ ]:
# Stack tensors on top of each others
x_stacked = torch.stack([a, a, a, a], dim=0)
x_stacked


tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

`dim=0`: This specifies the dimension along which the tensors will be stacked. In this case, `dim=0` means the tensors will be stacked along the first dimension ***(the rows)*** to create a new tensor.

In [ ]:
x_stacked = torch.stack([a, a, a, a], dim=1)
x_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

`dim=1`: This specifies the dimension along which the tensors will be stacked. In this case, `dim=1` means the tensors will be stacked along the second dimension ***(the columns)*** to create a new tensor.

**Squeezing**

In [ ]:
print(f"Pervious tensor: {a_reshaped}")
print(f"Previous shape: {a_reshaped.shape}")

# Squeezing
x_squeezed = a_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"\nNew shape: {x_squeezed.shape}")


Pervious tensor: tensor([[5.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])
Previous shape: torch.Size([9, 1])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

New shape: torch.Size([9])


**Un-Squeezing**


In [ ]:
print(f"Pervious target: {x_squeezed}")
print(f"Previous Shape: {x_squeezed.shape}")

# Unsqueezing
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew Tensor: {x_unsqueezed}")
print(f"\nNew Shape: {x_unsqueezed.shape}")


Pervious target: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous Shape: torch.Size([9])

New Tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])

New Shape: torch.Size([1, 9])


In [ ]:
print(f"Pervious target: {x_squeezed}")
print(f"Previous Shape: {x_squeezed.shape}")

# Unsqueezing
x_unsqueezed = x_squeezed.unsqueeze(dim=1)
print(f"\nNew Tensor: {x_unsqueezed}")
print(f"\nNew Shape: {x_unsqueezed.shape}")


Pervious target: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous Shape: torch.Size([9])

New Tensor: tensor([[5.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])

New Shape: torch.Size([9, 1])


`dim=0` changes or adds the dimension at the 0th index.

`dim=1` changes or adds the dimension at the 1st index.


In [ ]:
#torch.permute - rearranges the dimensions of a target is a specified order
x_original = torch.rand(size=(224, 224, 3)) #[height, width, colour_channels]

# permute the original tensors to rearrange the axis (or dim) order
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}") #[colour_channels, height, width]


Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


The permute function take input the dimension and changes the those dimensions to the dimensional positions they have been written.
-> i.e In the above expample the
`x_original.permute(2, 0, 1)` the original tensor's
* The 2nd Dimension will be permutted/changed to 0th dimension,
* The 0th will be permutted/changed to 1st dimension.
* The 1st dimension will be permutted/changed to 2nd dimensions.

**Note:** Here dimension are starting from the 0 to 2, like inedexes. therefore be carefull while understanding these dimensions. Dimensions in pyTorch tensors are difficult to understand therefore give more time to understand these units.


In [ ]:
x_original[0, 0, 0] = 782218
x_original[0, 0, 0], x_permuted[0, 0, 0]


(tensor(782218.), tensor(782218.))

In the above code we can see the if we change the original tensor values, the values in the permuted tensor will be changes as well.

 _______________Why?_____________

  Because the **permuted** tensor
 Returns a view of the original tensor input with its dimensions permuted.

 **Veiw** -> shares the same memory as the priginal tensor, changing the original tensor changes the view of the tensor.

### Indexing
Indexing with pyTorch is similar to indexing with Numpy.


In [ ]:
import torch
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
#  Index in the 0th Dimension
x[0]


tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
# Index in the 1st Dimension (dim=1)
x[0][0]


tensor([1, 2, 3])

In [ ]:
# Index of the 2nd dimension of the tnesor, (dim=2) last dimension
x[0][0][0]


tensor(1)

In [ ]:
# what if we do this?
x[0, 0, 0]
# Return same as x[0][0][0]

tensor(1)

In [ ]:
x[1][1][1]
# error because there is no dim=1, present only dim=0


IndexError: ignored

In [ ]:
# using ":"
x[:, 0]

tensor([[1, 2, 3]])

In [ ]:
# Get all the vlaues of 0th and 1st dimensions but only index 1 of 2nd dimension/.
x[:, :, 1]


tensor([[2, 5, 8]])

In [ ]:
# Get all values og 0th dimension but only 1 index value of 1st and 2nd dimension.
x[:, 1, 1]

tensor([5])

Difference between the above and below code is.
* In the above code we are selelcting all elements of 0th dim, along with the element 5 therefore comming with a [].
* In the below code we are only selecting the element 5. therefore coming with ().


In [ ]:
x[0, 1, 1]

tensor(5)

In [ ]:
x[0][1][:]

tensor([4, 5, 6])

In [ ]:
# retruning 9
x[0, 2, 2] # On;y 9

tensor(9)

In [ ]:
# retrun 3, 6, 9
x[0, :, 2]

tensor([3, 6, 9])

# Numpy and pyTorch
Numpy is popular scientific python numerical computing library.
And because of thos, pyTorch has functionality to interact with it.

* Data in NumPy want in PyTorch tensor -> `torch.from_numpy(ndarray)`
* PyTorch tensor -> NumPy -> `torch.Tensor.numpy()`

In [ ]:
# NumPy array to tensor
import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
array.dtype # Default datatype of numpy is Float64.

dtype('float64')

In [ ]:
torch.arange(1.0, 8.0).dtype # Deafult type of Tensor is Float32.

torch.float32

**Warning: When changing from Numpy -> Tensor, pytorch reflects numpy's default datatype of float64 unless specified otherwise.


In [ ]:
# Changing the dtype
tensor = torch.from_numpy(array).type(torch.float32)
tensor.dtype

torch.float32

In [ ]:
# Changing the value of array! will It change the tensor??
array = array + 1
array, tensor

# It doesn't effect the tensor.

(array([2., 3., 4., 5., 6., 7., 8.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [ ]:
# tensor to Numpy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

 # the datatype of the numpy array remains same as the tensor.

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
# change the tensor, what happens to "Numpy_tensor"??
tensor = tensor + 1
numpy_tensor, tensor

# it is uncahnged!

(array([1., 1., 1., 1., 1., 1., 1.], dtype=float32),
 tensor([2., 2., 2., 2., 2., 2., 2.]))

### Reproducibility (trying to take random out of random)

In short how neural network learns:
random numbers -> tensor operations -> making better representation of those random numbers of the data -> again -> again -> again.

to reduce the randomness in neural networks and pytorch comes the concept of **random seed**.
Essentially what the random seed does is "Flavour" the randomness.
*
Argumentative: According to Computer Scientist, computers are fundamentally deterministic. That means they run the smae steps over and over again. So, what the randomness we're doing here is reffered to as pseudo randomness or generated randomness. And the **Random Seed**, in Machine learning "Flavours" that randomeness.

* *Instead of relying on external random events, computers use complex algorithms to produce sequences of numbers that appear random. These sequences are not truly random but can be indistinguishable from true randomness for many practical purposes.*

* ***Random Seed in Machine Learning: In machine learning, random numbers are often used in various processes like initializing model parameters, shuffling datasets, or splitting data into training and testing sets. However, since computers generate pseudo-random numbers, they need a starting point or a reference value to begin the generation of these random sequences. This starting value is called the "random seed." By setting a specific random seed before running a machine learning algorithm, you can ensure that the sequence of pseudo-random numbers generated during the process remains the same each time you run the algorithm. This deterministic behavior is helpful in research and debugging as it allows you to replicate results and makes experiments more reproducible. However, it's also essential to be cautious with the choice of random seeds, as using the same seed for different experiments can lead to biased or overfitted results.***


In [ ]:
import torch

rand_A = torch.rand(3, 4)
rand_B = torch.rand(3, 4)
rand_A, rand_B

(tensor([[0.5913, 0.3811, 0.0679, 0.7805],
         [0.1285, 0.2527, 0.8782, 0.4879],
         [0.9265, 0.6091, 0.1261, 0.7698]]),
 tensor([[0.7895, 0.1188, 0.6285, 0.2221],
         [0.3197, 0.8425, 0.4500, 0.5997],
         [0.2803, 0.2577, 0.4538, 0.8037]]))

In [ ]:
print(rand_A == rand_B)
# Not equal. !!

tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:
# Making random but reproducible tensors.

RANDOM_SEED = 42 # why 42? it universal seed. but we can put any number to it.
torch.manual_seed(RANDOM_SEED) # Here this line of code works for one single statement after it.
rand_C = torch.rand(3,4)

torch.manual_seed(RANDOM_SEED) #if we don't use this line before creating the rand_D it will generate random number as defalut one. therefore mentioning it necessary before creating the rand_D tensor.
rand_D = torch.rand(3,4)

print(rand_C)
print(rand_D)
print(rand_C == rand_D)


tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


In pyTorch,  a random seed is also known as Manual Seed is a way flavor the randomness. So, these number as you see are still quite random, But the random seed hust makes them reproducible. So if the model was to be shared with other people, idealy they will have the same numerical output.

**Read More on**: https://pytorch.org/docs/stable/notes/randomness.html

**Random Seed**: More on wikki

### Running tensors and pytorch objects on the GPUs (Making faster computations)

GPUs -> Faster computation on numbers.

-> Google colab (free).

-> System GPUs - Personal GPU.

-> Cloud Services -> GCP, AWS, azure (paid)

In [ ]:
!nvidia-smi

Tue Aug  8 08:15:17 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.105.17   Driver Version: 525.105.17   CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   34C    P8     9W /  70W |      3MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [ ]:
# GPU access with pyTorch
import torch
torch.cuda.is_available()
# Cuda is nividia interface which allows us to use GPUs for numerical computing.

True

In [ ]:
# Device Agnostic Code
# Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device
# to check if the GPU is available for computing if not run on CPU.

'cuda'

In [ ]:
# Count the number of device
torch.cuda.device_count() # We can use multiple devices to rum models.
# pyTorch Agonstic documentation.

1

## Putting Tensors (AND models) on the GPUs

In [ ]:
tensor = torch.tensor([1, 2, 3])

# Tensor not on GPU
print(tensor, tensor.device)



tensor([1, 2, 3]) cpu


In [ ]:
# Shifting to GPUs
tensor_on_gpu = tensor.to(device)
tensor_on_gpu, tensor_on_gpu.device

(tensor([1, 2, 3], device='cuda:0'), device(type='cuda', index=0))

## Moving to CPU
* If the tensor is on GPU then it can't be converted to Numpy array.
*

In [ ]:
# Fixing GPU problem, setting it to cpu first then converting to numpy.
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

In [ ]:
tensor_on_gpu #GPU tensor is unchanged.

tensor([1, 2, 3], device='cuda:0')

pyTorch more on documentations. (Read)
-> Read on `torch.Tensor`.

-> Read on `torch.cuda`.

Extra Exercise on -> https://www.learnpytorch.io/00_pytorch_fundamentals/#exercises
